### ISSUE TITLE
Watson nodes not loading

### ISSUE THREAD

**Issue by mryani-UG** [watson-developer-cloud/node-red-node-watson#503]
I just cannot get the nodes to load.

-bash-5.1$ npm install node-red-node-watson
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/MIKE/node_modules/bufferutil
npm ERR! command failed
npm ERR! command /QOpenSys/pkgs/bin/bash -c -- node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.9.1 | os400 | ppc64
npm ERR! gyp info find Python using Python version 3.9.14 found at "/QOpenSys/pkgs/bin/python3"
npm ERR! gyp info spawn /QOpenSys/pkgs/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/MIKE/node_modules/bufferutil/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/MIKE/.cache/node-gyp/18.9.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/MIKE/.cache/node-gyp/18.9.1',
npm ERR! gyp info spawn args   '-Dnode_exp_file=/QOpenSys/pkgs/lib/nodejs18/include/node/node.exp',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/MIKE/.cache/node-gyp/18.9.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/MIKE/node_modules/bufferutil',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: gmake
npm ERR! gyp ERR! stack     at getNotFoundError (/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System OS400 7.4
npm ERR! gyp ERR! command "/QOpenSys/pkgs/lib/nodejs18/bin/node" "/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/MIKE/node_modules/bufferutil
npm ERR! gyp ERR! node -v v18.9.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/MIKE/.npm/_logs/2023-02-10T16_51_24_393Z-debug-0.log
-bash-5.1$

**Comment by chughts** [comment]
Looks like we are due a bump release. Any volunteers to take this on?
